# Locations for output
CACHED_DIR: 'cached_pages'
LAST_UPDATED_FILE: 'last_updated'
HISTORY_DIR: 'history'
CSV_NAME: 'scraped_televisions.csv'

# CSV Headers
HEADERS:
  - url
  - page
  - title
  - store
  - brand
  - tech
  - size
  - resolution
  - price

URI_OPTIONS:
  # Overstock rejects my requests with a regular Ruby User-Agent. Use Firefox.
  User-Agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0'
  From: 'spensterc@yahoo.com'
  Referer: 'http://www.ruby-lang.org/'

# Store Configuration ##########################################################

ALL_CONFIGS:
  - store: 'Amazon'
    type: 'html'
    base_url: 'https://www.amazon.com'
    search_url: '{base_url}/Televisions-Television-Video/s?rh=n%3A172659'
    item_query: '.s-result-item'
    title_query: 'img @alt'
    price_query: '.a-offscreen'
    url_query: 'a @href'
    pagination: '{search_url}&page={&page}'
    pages: 20

  - store: 'Best Buy'
    type: 'html'
    base_url: 'https://www.bestbuy.com'
    search_url: '{base_url}/site/tvs/all-flat-screen-tvs/abcat0101001.c?qp=condition_facet%3DCondition~New'
    item_query: '.sku-item'
    title_query: '.information .sku-title a'
    price_query: '.price-block .priceView-hero-price.priceView-customer-price'
    url_query: '.information .sku-title a @href'
    pagination: '{search_url}&cp={&page}'
    pages: 12

  - store: 'Costco'
    type: 'html'
    base_url: 'https://www.costco.com'
    search_url: '{base_url}/televisions.html'
    item_query: '.product'
    title_query: '.description a'
    price_query: '.caption .price'
    url_query: '.description a @href'
    pagination: '{search_url}'
    pages: 1

  - store: 'Ebay'
    type: 'html'
    base_url: 'https://www.ebay.com'
    search_url: '{base_url}/b/TVs/11071/bn_738302?LH_BIN=1&LH_FS=1&LH_RPA=1&rt=nc'
    item_query: '.s-item'
    title_query: '.s-item__title'
    price_query: '.s-item__price'
    url_query: '.s-item__link @href'
    pagination: '{search_url}&_pgn={&page}'
    pages: 20

  - store: 'Frys'
    type: 'html'
    base_url: 'https://www.frys.com'
    search_url: '{base_url}/category/Outpost/Video/Televisions'
    item_query: '.product'
    title_query: '.productDescp a'
    price_query: '.toGridPriceHeight ul li .red_txt'
    url_query: '.productDescp a @href'
    pagination: '{search_url}?page={&page}&start={&offset}&rows={per}'
    per: 20
    pages: 20

  - store: 'Newegg'
    type: 'html'
    base_url: 'https://www.newegg.com'
    search_url: '{base_url}/p/pl?N=100167585%204814'
    item_query: '.item-container'
    title_query: '.item-info .item-title'
    price_query: '.item-action .price-current'
    url_query: '.item-info a.item-title @href'
    pagination: '{search_url}&page={&page}'
    pages: 29

  - store: 'Overstock'
    type: 'json'
    base_url: 'https://www.overstock.com'
    search_url: '{base_url}/Electronics/Televisions/2171/cat.html?format=fusion'
    item_query: [products]
    title_query: [name]
    price_query: [pricing, current, priceBreakdown, price]
    url_query: [urls, productPage]
    pagination: '{search_url}&page={&page}'
    pages: 4

  - store: 'Target'
    type: 'json'
    base_url: 'https://www.target.com'
    search_url: '{base_url}/v2/plp/search/?category=5xtdj&default_purchasability_filter=true&pricing_store_id=1357&store_ids=1357&key=eb2551e4accc14f38cc42d32fbc2b2ea'
    item_query: [search_response, items, Item]
    title_query: [title]
    price_query: [price, current_retail]
    url_query: [url]
    pagination: '{search_url}&count={per}&offset={&offset}'
    per: 24
    pages: 3

  - store: 'Walmart'
    type: 'json'
    base_url: 'https://www.walmart.com'
    search_url: '{base_url}/search/api/preso?facet=condition%3ANew%7C%7Cvideo_panel_design%3AFlat'
    item_query: [items]
    title_query: [title]
    price_query: [primaryOffer, offerPrice]
    url_query: [productPageUrl]
    pagination: '{search_url}&page={&page}'
    pages: 13
